# Generated by Django 3.2.9 on 2021-11-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_dish_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
