# Generated by Django 3.2.9 on 2021-11-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211130_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
