# Generated by Django 3.2.9 on 2021-11-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211126_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
