# Generated by Django 3.2.9 on 2021-11-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_dish_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='ingredient',
            field=models.ManyToManyField(to='main.Ingredient'),
        ),
    ]
