# Generated by Django 3.2.9 on 2021-11-27 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_dish_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dish',
        ),
    ]
